# Generated by Django 2.0.5 on 2018-05-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.TextField(max_length=50)),
                ('good_price', models.TextField(max_length=50)),
                ('good_desc', models.TextField(max_length=50)),
                ('good_count', models.TextField(max_length=50)),
                ('good_phone', models.TextField(max_length=50)),
                ('good_img', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.TextField(max_length=50)),
                ('news_dt', models.DateTimeField(auto_now=True)),
                ('news_content', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=50)),
                ('user_pass', models.TextField(max_length=50)),
                ('user_phone', models.TextField(max_length=50)),
                ('user_role', models.TextField(max_length=50)),
                ('user_num', models.TextField(max_length=50)),
                ('user_addr', models.TextField(max_length=50)),
                ('user_real', models.TextField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='auth',
            field=models.ForeignKey(on_delete=None, to='user.User'),
        ),
        migrations.AddField(
            model_name='goods',
            name='good_user',
            field=models.ForeignKey(on_delete=None, to='user.User'),
        ),
    ]
