# Generated by Django 2.0.3 on 2018-05-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='good_count',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_desc',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_img',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_name',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_phone',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_price',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_content',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_count',
            field=models.TextField(default=None, max_length=11),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_phone',
            field=models.TextField(default=None, max_length=11),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_price',
            field=models.TextField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_title',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_addr',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_num',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_pass',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_real',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.TextField(default=None, max_length=50),
        ),
    ]
