# Generated by Django 2.0.3 on 2018-05-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180514_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='good_count',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_desc',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_img',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_name',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_phone',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='good_price',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_content',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_count',
            field=models.TextField(blank=True, default=None, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_dt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_phone',
            field=models.TextField(blank=True, default=None, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_price',
            field=models.TextField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_title',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_addr',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_num',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_pass',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_real',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
